name: $(date:yyyyMMdd)$(rev:.rr)

pr:
  - master

stages:
  - stage: build
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet build
            workingDirectory: $(System.DefaultWorkingDirectory)/p1-project

  - stage: test
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet test --collect:"XPlat Code Coverage"
            workingDirectory: ./p1-project

  - stage: pack
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: |
              docker login
              docker image build -f dockerfile -t fredbelotte/p1proj .
              docker image push fredbelotte/p1proj
              docker logout
            workingDirectory: ./p1-project

trigger:
  - master